services:
  - type: web
    name: nca-staging
    env: static
    branch: staging
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*
        name: X-Robots-Tag
        value: noindex, nofollow
